app_name: "GrayLink"
debug: false

monitor:
  scan_interval: 300
  google_drive:
    client_id: ""
    client_secret: ""
    token_file: "data/gdrive_token.json"

symlink:
  source_dir: "/mnt/media/nastool"
  target_dir: "/mnt/nastool-nfo"
  preserve_structure: true
  backup_on_conflict: true
  backup_dir: "data/backup"
  max_backups: 5

emby:
  server_url: "http://localhost:8096"
  api_key: null
  auto_refresh: true
  refresh_delay: 10
  path_mapping: {}
  library_paths: []
  timeout: 30
  max_retries: 3
  retry_delay: 5

database:
  url: "sqlite+aiosqlite:///data/graylink.db"
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  batch_size: 1000

security:
  secret_key: ""
  algorithm: "HS256"
  access_token_expire_minutes: 30

cache:
  strategy: "ttl"
  default_ttl: 300
  maxsize: 1000
  cleanup_interval: 3600 