version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend/graylink-web
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
    volumes:
      - ./frontend/graylink-web/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - graylink-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - graylink-network

networks:
  graylink-network:
    driver: bridge 