version: '3'

services:
  graylink:
    build: .
    ports:
      - "8728:8728"
      - "8000:8000"
    volumes:
      - ./config:/app/backend/config
      - ./data:/app/backend/data
      - /path/to/gdrive:/gdrive:shared
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped 